// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myrmfnybgjtogmordiqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cm1mbnliZ2p0b2dtb3JkaXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTkwMjAsImV4cCI6MjA2OTc3NTAyMH0.AwvOiRyl9n_1_-kndA_By7KiUh6N-OPIW6NJ-5ZiBTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});